os: linux
dist: xenial
language: python
install:
  - pip install -r requirements.txt
script:
  - pip wheel . -w wheelhouse
  - ls wheelhouse
env:
  global:
  - TWINE_USERNAME=__token__
after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python -m pip install twine
      python -m twine upload --verbose wheelhouse/*.whl
    fi
